### ISSUE TITLE
Python

### ISSUE THREAD

**Issue by masaccio** [j-brooke/FracturedJson#15]
Before I start - are you aware of a python port of your work?

**Comment by j-brooke** [comment]
> Before I start - are you aware of a python port of your work?

I'm not aware of any, but if you get one going, please let me know!

**Comment by masaccio** [comment]
OK I have a first pass which is essentially a manual port of your JS version to equivalent Python. Do you have tests you use?

**Comment by j-brooke** [comment]
> OK I have a first pass which is essentially a manual port of your JS version to equivalent Python. Do you have tests you use?

I don't have any automated tests, no. (I planned to write some before doing any more major work on the project.)  I do have a variety of files I've used for testing.  I'll have to look and see if they're safe to share.

**Comment by masaccio** [comment]
Looks like your Wiki has a bunch of examples I can use and that's throwing up some helpful bugs which is a good start.

The fork now lives at https://github.com/masaccio/compact-json and the point at which it actually starts getting useful and I think I've got most of the bugs out I will publish to PyPI.

If you want different attribution do let me know -- the hard work was all yours and I was just looking for some better JSON formatting for a different Python package.

**Comment by j-brooke** [comment]
Nice work.  I'm good with the attribution how you've got it, thanks.  The important thing is that people be able to move between the repos to find what they're looking for.

I've added a couple links to your repo - on the web formatter Github Page and wiki.  Please let me know if you'd like any of that changed.

**Comment by j-brooke** [comment]
Closing this issue since @masaccio 's Python port is up and running.
