### ISSUE TITLE
net6 support?

### ISSUE THREAD

**Issue by dviry** [j-brooke/FracturedJson#19]
I know I could just copy the source code, but I'd rather use the published NuGet - any chance of having it also for net6?

Thanks in advance

**Comment by j-brooke** [comment]
Based on my testing, the NuGet package is already compatible with .NET 6.  NuGet imports it fine.  It compiles without any warnings.  It runs on systems where only newer versions of .NET are installed.

Maybe I'm violating some best practice, and if so I'd like to learn.  My goal, of course, was to make the package as available as possible.

Can you help me understand what problems you're running into?

**Comment by dviry** [comment]
Compiling in DevOps works fine, as well as in VS22. But running dotnet restore throws the following error:

```
error NU1202: Package FracturedJson 2.2.0 is not compatible with net60 (.NETFramework,Version=v6.0). Package FracturedJson 2.2.0 supports: netcoreapp3.1 (.NETCoreApp,Version=v3.1) 
```

Not sure how critical that is, just wanted to share.

Thanks

**Comment by j-brooke** [comment]
Hmm.  I appreciate the info, but I don't know what to do with it.  It's working for me with existing projects and brand new ones.

**Comment by j-brooke** [comment]
I've just pushed the v3.0.0 package to NuGet.  It's set to netstandard2.0.  Hopefully it gives you less trouble.  If you choose to upgrade to it, please let me know how it goes.  (See changelog for a couple small changes you'll need to make if so.)

**Comment by j-brooke** [comment]
I'm closing this since I haven't heard anything new and the change to v3 hopefully fixed whatever it was.
