### ISSUE TITLE
Plugin for VSCode?

### ISSUE THREAD

**Issue by ChronoDK** [j-brooke/FracturedJson#2]
I love this formatter and use the web-version regularly. It would be really useful to have it as a plugin to VSCode or maybe Notepad++, as none of the other available formatters seem able to do it as nicely as your tool.

Any plans to do that?

**Comment by j-brooke** [comment]
Thanks for your interest.  

I don't have any immediate plans to write a plugin.  I love VSCode and I think that would be an excellent target.  But I haven't researched how things are done in the VSCode plugin world.  In particular, I don't know how to handle:

1. key bindings
2. exposing settings to the user
3. parse-failure handling

I'm happy to entertain suggestions.

**Comment by ChronoDK** [comment]
I'm no expert, but the code formatters I enjoy using in VSCode are of the format-on-save type. So when I save the file, it is automatically formatted. Settings are changed through the command palette, and stored in json files. Usually each project will have a settings.json stored in their .vscode folder with project specific settings, but there are global settings as well.

**Comment by j-brooke** [comment]
I created a VS Code extension.  The functionality is pretty basic, but hopefully useful.

The repo is here: https://github.com/j-brooke/FracturedJsonVSC

The extension's marketplace page is here: https://marketplace.visualstudio.com/items?itemName=j-brooke.fracturedjsonvsc

**Comment by ChronoDK** [comment]
Amazing, just installed it and fixed a few documents I had. Great work - love this tool!
