### ISSUE TITLE
move closing brackets up?

### ISSUE THREAD

**Issue by SaraCPickett** [j-brooke/FracturedJson#24]
If would be cool if the formatter could move closing brackets up and condense them a single line, for even more compactness in cases where inlining is not possible.  For example:

```
{
    "otherkeyX": [
        {
            "somekey1": {
                "somekey2": "somevalueA",
                "somekey3": {"somekey4": "somevalueB"}
            }
        }
    ],
    "otherkeyY": []
}
```

Could be:
```
{
    "otherkeyX": [
        {
            "somekey1": {
                "somekey2": "somevalueA",
                "somekey3": {"somekey4": "somevalueB"}}}],
    "otherkeyY": [] }
```

Basically, the indentation of the next line clues you in as to how many brackets have been closed.  It's sort of horrible, but people could turn it on or off with settings, and it *is* more compact!

**Comment by j-brooke** [comment]
Interesting idea.  Is this a formatting approach that people currently use, or a brand new idea?  

It makes it hard to visually match up braces, but if you trust the indentation then you know all you need to, I suppose.  Editing a document in this style seems like it would be trickier, but for viewing I can see the appeal.

I played around with implementing it.  The big problem I ran into is line lengths.  Knowing how many closing brackets you can pile on without exceeding the limit doesn't fit well with the current logic.

**Comment by SaraCPickett** [comment]
[Sorry, didn’t mean to close this, just misclicked. Although of course you can if you want.]
 Yeah, it only applies to trusted json. Although if the json is really invalid, all bets are off with regards to any formatting working.
I can see the problem with line length, although for me it wouldn’t be too much of an issue. I’ve got a fairly standard line width configured but the window is much larger, so going a few characters over isn't a big deal. Even more than that doesn’t matter, because all that’s going to be over there is a bunch of brackets so I don’t need to scroll sideways to see them, since as you say all the structure ends up being indicated by the indentation amount. So the line length limit could become some sort of soft line length hint.

**Comment by SaraCPickett** [comment]
It’s sort of like the arguments about C style blocks versus Python. It seems ridiculous that the whitespace in Python has meaning, but if you write an if statement in C without the brackets, but indent more than one statement, everyone’s going to read those other statements as part of the block, even though the compiler doesn’t. 
So since the people are basing their understanding on the whitespace, you might as well lean on that a little more. In the case of json, I’m not saying you should ignore the brackets(!) but I think it’s okay to let the humans lean on the whitespace to get meaning out of the json, since the formatter can make the whitespace be correct.

**Comment by j-brooke** [comment]
I'm closing this for now.  I appreciate the suggestion, but I don't think there's enough interest to justify creating and then maintaining the feature.
