### ISSUE TITLE
NestedBracketPadding intended behavior?

### ISSUE THREAD

**Issue by manvithn** [j-brooke/FracturedJson#26]
Currently, it makes tables like this look inconsistent. Not sure if this is intended, but it feels like empty array should be treated differently?
```
"foo": [
  { "bar": "A", "nums": [0, 2] },
  {"bar": "B", "nums": []},
  { "bar": "C", "nums": [0, 2] },
  { "bar": "D", "nums": [1] },
  {"bar": "E", "nums": []},
  {"bar": "F", "nums": []}
],
```
Ideally, it would look like this:
```
"foo": [
  { "bar": "A", "nums": [0, 2] },
  { "bar": "B", "nums": [] },
  { "bar": "C", "nums": [0, 2] },
  { "bar": "D", "nums": [1] },
  { "bar": "E", "nums": [] },
  { "bar": "F", "nums": [] }
],
```

**Comment by j-brooke** [comment]
It is intended behavior, but there's another setting to control it.  And I agree - in this case it looks unpleasant.

You mentioned the setting [NestedBracketPadding](https://github.com/j-brooke/FracturedJson/wiki/Options#nestedbracketpadding) (`true|false`).  It controls whether to add spaces inside brackets of complex objects/arrays.  But there's also [SimpleBracketPadding](https://github.com/j-brooke/FracturedJson/wiki/Options#simplebracketpadding) (`true|false`), which controls whether to add spaces inside simple arrays/objects - that is, ones that only contain primitives and/or empty arrays/objects.

I think you'll see the behavior you want if you set both of those to `true`.

Examples -

`SimpleBracketPadding=false; NestedBracketPadding=false`
```
[
    {"bar": "A", "nums": [0, 2]},
    {"bar": "B", "nums": []},
    {"bar": "C", "nums": [0, 2]},
    {"bar": "D", "nums": [1]},
    {"bar": "E", "nums": []},
    {"bar": "F", "nums": []}
]
```

`SimpleBracketPadding=false; NestedBracketPadding=true`
```
[
    { "bar": "A", "nums": [0, 2] },
    {"bar": "B", "nums": []},
    { "bar": "C", "nums": [0, 2] },
    { "bar": "D", "nums": [1] },
    {"bar": "E", "nums": []},
    {"bar": "F", "nums": []}
]
```

`SimpleBracketPadding=true; NestedBracketPadding=false`
```
[
    {"bar": "A", "nums": [ 0, 2 ]},
    { "bar": "B", "nums": [] },
    {"bar": "C", "nums": [ 0, 2 ]},
    {"bar": "D", "nums": [ 1 ]},
    { "bar": "E", "nums": [] },
    { "bar": "F", "nums": [] }
]
```

`SimpleBracketPadding=true; NestedBracketPadding=true`
```
[
    { "bar": "A", "nums": [ 0, 2 ] },
    { "bar": "B", "nums": [] },
    { "bar": "C", "nums": [ 0, 2 ] },
    { "bar": "D", "nums": [ 1 ] },
    { "bar": "E", "nums": [] },
    { "bar": "F", "nums": [] }
]
```

[MaxTableRowComplexity](https://github.com/j-brooke/FracturedJson/wiki/Options#maxtablerowcomplexity) might be worth playing with too.  Table-formatted arrays/objects look good with some data, but not all.

`MaxTableRowComplexity=2`
```
[
    { "bar": "A", "nums": [ 0, 2 ] },
    { "bar": "B", "nums": [      ] },
    { "bar": "C", "nums": [ 0, 2 ] },
    { "bar": "D", "nums": [ 1    ] },
    { "bar": "E", "nums": [      ] },
    { "bar": "F", "nums": [      ] }
]
```

(If I had it to do over, I probably wouldn't have split bracket padding into two settings like this.  It seemed to make sense in version 1, so I'm stuck with it.  :) )

**Comment by manvithn** [comment]
Alright, I think I'm going to go with `SimpleBracketPadding=false; NestedBracketPadding=false`, thanks for the examples!
