### ISSUE TITLE
Different format options for arrays and objects

### ISSUE THREAD

**Issue by arikw** [j-brooke/FracturedJson#30]
Hello,
Thank you for your great work.
Would you please consider adding an option to keep objects multiline and format only the arrays?
I'm trying to achieve the following:
e.g.
```js
// original object:
{
  a: { b: [3, 4 ,5] },
  d: [9, 12]
}
// formatted object:
{
  a: {
    b: [3, 4, 5]
  },
  d: [9, 12]
}
```

Is it possible to achieve with current options?

**Comment by j-brooke** [comment]
For this particular example, you'll get the desired output if you set `MaxInlineComplexity=1` (assuming the other settings are the defaults).

```
{
    "a": {
        "b": [3, 4, 5]
    },
    "d": [9, 12]
}
```

But that's not a general solution to what you're asking: less complex objects will still be inlined as in this example:

```
{
    "a": {
        "b": [3, 4, 5]
    },
    "d": [9, 12],
    "w": {"x": 7}
}
```

If you were to set `MaxInlineComplexity=0` while leaving `MaxCompactArrayComplexity=1` (or higher), you'd get array values sharing lines, but they'd still be on different lines than the opening and closing array brackets.  For example:

```
{
    "a": {
        "b": [
            3, 4, 5
        ]
    },
    "d": [
         9, 12
    ],
    "w": {
        "x": 7
    }
}
```

Neither of these do exactly what it sounds like you want, but maybe if you play with those settings (and `MaxTableRowComplexity`) you can find something that works for you.
