### ISSUE TITLE
Remove trailing whitespace

### ISSUE THREAD

**Issue by cmeeren** [j-brooke/FracturedJson#34]
FracturedJson sometimes adds trailing whitespace to lines in the formatted output. It would be nice if FracturedJson trimmed all lines. This would for example make snapshot tests simpler to debug, where some editors strip whitespace which causes the before/after files to differ in this regard.

**Comment by j-brooke** [comment]
There's a setting for that.  Use `OmitTrailingWhitespace = true`.

I introduced that in version 3.1.0, and made the default `false` for backward compatibility.  It was introduced in a minor version update, so breaking changes would have been inappropriate.  Now that you mention it, though, I wish I had changed the default to `true` for version 4.0.0.

**Comment by cmeeren** [comment]
Thanks for the clarification! Are there other settings I should know about where you would ideally they had different defaults?

**Comment by j-brooke** [comment]
>Are there other settings I should know about where you would ideally they had different defaults?

No - I just looked through the list and I'm happy with the other defaults.  Although I have had some criticisms with the default `NumberListAlignment` being `Normalize` ([wiki](https://github.com/j-brooke/FracturedJson/wiki/Options#numberlistalignment)).  Some people would prefer a default that keeps the exact number representation from the original document.
